name: create tag
on: push
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.2.x"
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: package-version-to-git-tag
        continue-on-error: true
        run: 
          git tag -a v${{ env.PACKAGE_VERSION }} && git push origin v${{ env.PACKAGE_VERSION }}