name: create tag
on: push
jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      can_release: ${{ steps.push_tag.outputs.can_release }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.2.x"
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: git setting
        run: |
          git config --local user.email "{{ github.actor }}@users.noreply.github.com"
          git config --local user.name "{{ github.actor }}"
      - name: push tag
        id: push_tag
        continue-on-error: true
        run: |
          set -eux
          git tag -a v${{ env.PACKAGE_VERSION }} -m "Release v${{ env.PACKAGE_VERSION }}" && git push origin v${{ env.PACKAGE_VERSION }} && echo "::set-output can_release=true"
  call-workflow:
    needs: [create-tag]
    if: ${{ needs.create-tag.outputs.can_release }} == 'true'
    uses: ./.github/workflows/publish.yml