name: lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.2.x"
      - name: dependencies insta;;
        run: yarn install
      - name: lint
        run: yarn lint